remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme 

title: [Remote sensing of suspended sediment]
description: [A satellite based approach for monitoring suspended sediment concentration using Landsat and Sentinel]